//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     //
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TmsCommonDataService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BasicServiceSearchModel", Namespace="http://schemas.datacontract.org/2004/07/Shangpin.Logistic.ServiceLibrary.SearchEn" +
        "tity")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TmsCommonDataService.ValueAddedServiceFeeServiceSearchModel))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TmsCommonDataService.ContractServiceSearchModel))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TmsCommonDataService.CustomsPortServiceSearchModel))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TmsCommonDataService.LogisticsCompanyServiceSearchModel))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TmsCommonDataService.WarehouseServiceSearchModel))]
    public partial class BasicServiceSearchModel : object
    {
        
        private System.Collections.Generic.List<int> IdsField;
        
        private System.Nullable<bool> IsEnableField;
        
        private System.Collections.Generic.List<string> NamesField;
        
        private System.Collections.Generic.List<string> NosField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<int> Ids
        {
            get
            {
                return this.IdsField;
            }
            set
            {
                this.IdsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> IsEnable
        {
            get
            {
                return this.IsEnableField;
            }
            set
            {
                this.IsEnableField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<string> Names
        {
            get
            {
                return this.NamesField;
            }
            set
            {
                this.NamesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<string> Nos
        {
            get
            {
                return this.NosField;
            }
            set
            {
                this.NosField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ValueAddedServiceFeeServiceSearchModel", Namespace="http://schemas.datacontract.org/2004/07/Shangpin.Logistic.ServiceLibrary.SearchEn" +
        "tity")]
    public partial class ValueAddedServiceFeeServiceSearchModel : TmsCommonDataService.BasicServiceSearchModel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ContractServiceSearchModel", Namespace="http://schemas.datacontract.org/2004/07/Shangpin.Logistic.ServiceLibrary.SearchEn" +
        "tity")]
    public partial class ContractServiceSearchModel : TmsCommonDataService.BasicServiceSearchModel
    {
        
        private System.Collections.Generic.List<int> LogisticsCompanyIdsField;
        
        private System.Collections.Generic.List<string> LogisticsCompanyNosField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<int> LogisticsCompanyIds
        {
            get
            {
                return this.LogisticsCompanyIdsField;
            }
            set
            {
                this.LogisticsCompanyIdsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<string> LogisticsCompanyNos
        {
            get
            {
                return this.LogisticsCompanyNosField;
            }
            set
            {
                this.LogisticsCompanyNosField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CustomsPortServiceSearchModel", Namespace="http://schemas.datacontract.org/2004/07/Shangpin.Logistic.ServiceLibrary.SearchEn" +
        "tity")]
    public partial class CustomsPortServiceSearchModel : TmsCommonDataService.BasicServiceSearchModel
    {
        
        private System.Nullable<short> IsRealField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<short> IsReal
        {
            get
            {
                return this.IsRealField;
            }
            set
            {
                this.IsRealField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LogisticsCompanyServiceSearchModel", Namespace="http://schemas.datacontract.org/2004/07/Shangpin.Logistic.ServiceLibrary.SearchEn" +
        "tity")]
    public partial class LogisticsCompanyServiceSearchModel : TmsCommonDataService.BasicServiceSearchModel
    {
        
        private System.Nullable<TmsCommonDataService.ContractStatus> ContractStatusField;
        
        private System.Nullable<TmsCommonDataService.CooperativeStatusEnum> CooperativeStatusField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<TmsCommonDataService.ContractStatus> ContractStatus
        {
            get
            {
                return this.ContractStatusField;
            }
            set
            {
                this.ContractStatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<TmsCommonDataService.CooperativeStatusEnum> CooperativeStatus
        {
            get
            {
                return this.CooperativeStatusField;
            }
            set
            {
                this.CooperativeStatusField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WarehouseServiceSearchModel", Namespace="http://schemas.datacontract.org/2004/07/Shangpin.Logistic.ServiceLibrary.SearchEn" +
        "tity")]
    public partial class WarehouseServiceSearchModel : TmsCommonDataService.BasicServiceSearchModel
    {
        
        private System.Collections.Generic.List<int> LogisticsCompanyIdsField;
        
        private System.Collections.Generic.List<string> LogisticsCompanyNosField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<int> LogisticsCompanyIds
        {
            get
            {
                return this.LogisticsCompanyIdsField;
            }
            set
            {
                this.LogisticsCompanyIdsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<string> LogisticsCompanyNos
        {
            get
            {
                return this.LogisticsCompanyNosField;
            }
            set
            {
                this.LogisticsCompanyNosField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ContractStatus", Namespace="http://schemas.datacontract.org/2004/07/Shangpin.Logistic.Model.Enum.Basic")]
    public enum ContractStatus : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Invalid = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BeReady = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Valid = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CooperativeStatusEnum", Namespace="http://schemas.datacontract.org/2004/07/Shangpin.Logistic.Model.Enum.Basic")]
    public enum CooperativeStatusEnum : byte
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Normal = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PlanToClearingAccount = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InClearingAccount = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        HasBeenClearingAccount = 3,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WarehouseServiceModel", Namespace="http://schemas.datacontract.org/2004/07/Shangpin.Logistic.ServiceLibrary.Entity")]
    public partial class WarehouseServiceModel : object
    {
        
        private TmsCommonDataService.AreaServiceModel AreaField;
        
        private int AreaIDField;
        
        private string AreaIDsField;
        
        private string AreaNameField;
        
        private string AreaNamesField;
        
        private string BusinessEntityField;
        
        private string ConsigneeField;
        
        private string ConsigneeEmailField;
        
        private string ConsigneeMobilephoneField;
        
        private string ConsigneeTelephoneField;
        
        private string ConsignerField;
        
        private string ConsignerEmailField;
        
        private string ConsignerMobilephoneField;
        
        private string ConsignerTelephoneField;
        
        private TmsCommonDataService.CustomsPortServiceModel CustomsPortField;
        
        private int CustomsPortIDField;
        
        private bool IsCustomsClearanceField;
        
        private bool IsEnableField;
        
        private bool IsPhotosField;
        
        private bool IsTaxFreeField;
        
        private TmsCommonDataService.LogisticsCompanyServiceModel LogisticsCompanyField;
        
        private int LogisticsCompanyIDField;
        
        private string LogisticsCompanyNOField;
        
        private string LogisticsCompanyNameField;
        
        private int OrderByField;
        
        private string PortNameField;
        
        private TmsCommonDataService.SettlementPrincipalServiceModel SettlementPrincipalField;
        
        private decimal TaxRateField;
        
        private string ToDeleteAreaIDsField;
        
        private string ToInsertAreaIDsField;
        
        private int TranshipmentWarehouseIDField;
        
        private string WarehouseAddressField;
        
        private string WarehouseManagerField;
        
        private string WarehouseNameField;
        
        private string WarehouseNoField;
        
        private string WarehousePostcodeField;
        
        private string WarehouseRemarkField;
        
        private string WarehouseShippingAddressField;
        
        private string WarehouseTypeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TmsCommonDataService.AreaServiceModel Area
        {
            get
            {
                return this.AreaField;
            }
            set
            {
                this.AreaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AreaID
        {
            get
            {
                return this.AreaIDField;
            }
            set
            {
                this.AreaIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AreaIDs
        {
            get
            {
                return this.AreaIDsField;
            }
            set
            {
                this.AreaIDsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AreaName
        {
            get
            {
                return this.AreaNameField;
            }
            set
            {
                this.AreaNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AreaNames
        {
            get
            {
                return this.AreaNamesField;
            }
            set
            {
                this.AreaNamesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BusinessEntity
        {
            get
            {
                return this.BusinessEntityField;
            }
            set
            {
                this.BusinessEntityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Consignee
        {
            get
            {
                return this.ConsigneeField;
            }
            set
            {
                this.ConsigneeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ConsigneeEmail
        {
            get
            {
                return this.ConsigneeEmailField;
            }
            set
            {
                this.ConsigneeEmailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ConsigneeMobilephone
        {
            get
            {
                return this.ConsigneeMobilephoneField;
            }
            set
            {
                this.ConsigneeMobilephoneField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ConsigneeTelephone
        {
            get
            {
                return this.ConsigneeTelephoneField;
            }
            set
            {
                this.ConsigneeTelephoneField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Consigner
        {
            get
            {
                return this.ConsignerField;
            }
            set
            {
                this.ConsignerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ConsignerEmail
        {
            get
            {
                return this.ConsignerEmailField;
            }
            set
            {
                this.ConsignerEmailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ConsignerMobilephone
        {
            get
            {
                return this.ConsignerMobilephoneField;
            }
            set
            {
                this.ConsignerMobilephoneField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ConsignerTelephone
        {
            get
            {
                return this.ConsignerTelephoneField;
            }
            set
            {
                this.ConsignerTelephoneField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TmsCommonDataService.CustomsPortServiceModel CustomsPort
        {
            get
            {
                return this.CustomsPortField;
            }
            set
            {
                this.CustomsPortField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CustomsPortID
        {
            get
            {
                return this.CustomsPortIDField;
            }
            set
            {
                this.CustomsPortIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsCustomsClearance
        {
            get
            {
                return this.IsCustomsClearanceField;
            }
            set
            {
                this.IsCustomsClearanceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsEnable
        {
            get
            {
                return this.IsEnableField;
            }
            set
            {
                this.IsEnableField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsPhotos
        {
            get
            {
                return this.IsPhotosField;
            }
            set
            {
                this.IsPhotosField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsTaxFree
        {
            get
            {
                return this.IsTaxFreeField;
            }
            set
            {
                this.IsTaxFreeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TmsCommonDataService.LogisticsCompanyServiceModel LogisticsCompany
        {
            get
            {
                return this.LogisticsCompanyField;
            }
            set
            {
                this.LogisticsCompanyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LogisticsCompanyID
        {
            get
            {
                return this.LogisticsCompanyIDField;
            }
            set
            {
                this.LogisticsCompanyIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LogisticsCompanyNO
        {
            get
            {
                return this.LogisticsCompanyNOField;
            }
            set
            {
                this.LogisticsCompanyNOField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LogisticsCompanyName
        {
            get
            {
                return this.LogisticsCompanyNameField;
            }
            set
            {
                this.LogisticsCompanyNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OrderBy
        {
            get
            {
                return this.OrderByField;
            }
            set
            {
                this.OrderByField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PortName
        {
            get
            {
                return this.PortNameField;
            }
            set
            {
                this.PortNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TmsCommonDataService.SettlementPrincipalServiceModel SettlementPrincipal
        {
            get
            {
                return this.SettlementPrincipalField;
            }
            set
            {
                this.SettlementPrincipalField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal TaxRate
        {
            get
            {
                return this.TaxRateField;
            }
            set
            {
                this.TaxRateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ToDeleteAreaIDs
        {
            get
            {
                return this.ToDeleteAreaIDsField;
            }
            set
            {
                this.ToDeleteAreaIDsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ToInsertAreaIDs
        {
            get
            {
                return this.ToInsertAreaIDsField;
            }
            set
            {
                this.ToInsertAreaIDsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TranshipmentWarehouseID
        {
            get
            {
                return this.TranshipmentWarehouseIDField;
            }
            set
            {
                this.TranshipmentWarehouseIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WarehouseAddress
        {
            get
            {
                return this.WarehouseAddressField;
            }
            set
            {
                this.WarehouseAddressField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WarehouseManager
        {
            get
            {
                return this.WarehouseManagerField;
            }
            set
            {
                this.WarehouseManagerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WarehouseName
        {
            get
            {
                return this.WarehouseNameField;
            }
            set
            {
                this.WarehouseNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WarehouseNo
        {
            get
            {
                return this.WarehouseNoField;
            }
            set
            {
                this.WarehouseNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WarehousePostcode
        {
            get
            {
                return this.WarehousePostcodeField;
            }
            set
            {
                this.WarehousePostcodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WarehouseRemark
        {
            get
            {
                return this.WarehouseRemarkField;
            }
            set
            {
                this.WarehouseRemarkField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WarehouseShippingAddress
        {
            get
            {
                return this.WarehouseShippingAddressField;
            }
            set
            {
                this.WarehouseShippingAddressField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WarehouseType
        {
            get
            {
                return this.WarehouseTypeField;
            }
            set
            {
                this.WarehouseTypeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AreaServiceModel", Namespace="http://schemas.datacontract.org/2004/07/Shangpin.Logistic.ServiceLibrary.Entity")]
    public partial class AreaServiceModel : object
    {
        
        private string AreaChNameField;
        
        private string AreaEnNameField;
        
        private int AreaIDField;
        
        private string AreaNoField;
        
        private short ChildrenDefaultOrderValueField;
        
        private bool IsEnableField;
        
        private bool IsLeafField;
        
        private int LayerField;
        
        private string ParentAreaChNameField;
        
        private string ParentAreaEnNameField;
        
        private int ParentIDField;
        
        private string ParentIDsField;
        
        private string PatchField;
        
        private int SortOrderField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AreaChName
        {
            get
            {
                return this.AreaChNameField;
            }
            set
            {
                this.AreaChNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AreaEnName
        {
            get
            {
                return this.AreaEnNameField;
            }
            set
            {
                this.AreaEnNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AreaID
        {
            get
            {
                return this.AreaIDField;
            }
            set
            {
                this.AreaIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AreaNo
        {
            get
            {
                return this.AreaNoField;
            }
            set
            {
                this.AreaNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short ChildrenDefaultOrderValue
        {
            get
            {
                return this.ChildrenDefaultOrderValueField;
            }
            set
            {
                this.ChildrenDefaultOrderValueField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsEnable
        {
            get
            {
                return this.IsEnableField;
            }
            set
            {
                this.IsEnableField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsLeaf
        {
            get
            {
                return this.IsLeafField;
            }
            set
            {
                this.IsLeafField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Layer
        {
            get
            {
                return this.LayerField;
            }
            set
            {
                this.LayerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ParentAreaChName
        {
            get
            {
                return this.ParentAreaChNameField;
            }
            set
            {
                this.ParentAreaChNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ParentAreaEnName
        {
            get
            {
                return this.ParentAreaEnNameField;
            }
            set
            {
                this.ParentAreaEnNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ParentID
        {
            get
            {
                return this.ParentIDField;
            }
            set
            {
                this.ParentIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ParentIDs
        {
            get
            {
                return this.ParentIDsField;
            }
            set
            {
                this.ParentIDsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Patch
        {
            get
            {
                return this.PatchField;
            }
            set
            {
                this.PatchField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SortOrder
        {
            get
            {
                return this.SortOrderField;
            }
            set
            {
                this.SortOrderField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CustomsPortServiceModel", Namespace="http://schemas.datacontract.org/2004/07/Shangpin.Logistic.ServiceLibrary.Entity")]
    public partial class CustomsPortServiceModel : object
    {
        
        private int AreaIDField;
        
        private string AreaNameField;
        
        private string ButtManLinkModeField;
        
        private int CustomsPortIDField;
        
        private int InletModeField;
        
        private bool IsButtField;
        
        private bool IsEnabledField;
        
        private int IsRealField;
        
        private string LinkManMailField;
        
        private string LinkManMobileField;
        
        private string LinkManPhoneField;
        
        private int MasterCustomsPortIDField;
        
        private int OrderByField;
        
        private string PortButtManField;
        
        private string PortFaxField;
        
        private string PortLinkManField;
        
        private string PortNOField;
        
        private string PortNameField;
        
        private string PortServicesAddressField;
        
        private string PortServicesPhoneField;
        
        private string PortServicesURLField;
        
        private string RemarkField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AreaID
        {
            get
            {
                return this.AreaIDField;
            }
            set
            {
                this.AreaIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AreaName
        {
            get
            {
                return this.AreaNameField;
            }
            set
            {
                this.AreaNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ButtManLinkMode
        {
            get
            {
                return this.ButtManLinkModeField;
            }
            set
            {
                this.ButtManLinkModeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CustomsPortID
        {
            get
            {
                return this.CustomsPortIDField;
            }
            set
            {
                this.CustomsPortIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int InletMode
        {
            get
            {
                return this.InletModeField;
            }
            set
            {
                this.InletModeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsButt
        {
            get
            {
                return this.IsButtField;
            }
            set
            {
                this.IsButtField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsEnabled
        {
            get
            {
                return this.IsEnabledField;
            }
            set
            {
                this.IsEnabledField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IsReal
        {
            get
            {
                return this.IsRealField;
            }
            set
            {
                this.IsRealField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LinkManMail
        {
            get
            {
                return this.LinkManMailField;
            }
            set
            {
                this.LinkManMailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LinkManMobile
        {
            get
            {
                return this.LinkManMobileField;
            }
            set
            {
                this.LinkManMobileField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LinkManPhone
        {
            get
            {
                return this.LinkManPhoneField;
            }
            set
            {
                this.LinkManPhoneField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MasterCustomsPortID
        {
            get
            {
                return this.MasterCustomsPortIDField;
            }
            set
            {
                this.MasterCustomsPortIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OrderBy
        {
            get
            {
                return this.OrderByField;
            }
            set
            {
                this.OrderByField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PortButtMan
        {
            get
            {
                return this.PortButtManField;
            }
            set
            {
                this.PortButtManField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PortFax
        {
            get
            {
                return this.PortFaxField;
            }
            set
            {
                this.PortFaxField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PortLinkMan
        {
            get
            {
                return this.PortLinkManField;
            }
            set
            {
                this.PortLinkManField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PortNO
        {
            get
            {
                return this.PortNOField;
            }
            set
            {
                this.PortNOField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PortName
        {
            get
            {
                return this.PortNameField;
            }
            set
            {
                this.PortNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PortServicesAddress
        {
            get
            {
                return this.PortServicesAddressField;
            }
            set
            {
                this.PortServicesAddressField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PortServicesPhone
        {
            get
            {
                return this.PortServicesPhoneField;
            }
            set
            {
                this.PortServicesPhoneField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PortServicesURL
        {
            get
            {
                return this.PortServicesURLField;
            }
            set
            {
                this.PortServicesURLField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Remark
        {
            get
            {
                return this.RemarkField;
            }
            set
            {
                this.RemarkField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LogisticsCompanyServiceModel", Namespace="http://schemas.datacontract.org/2004/07/Shangpin.Logistic.ServiceLibrary.Entity")]
    public partial class LogisticsCompanyServiceModel : object
    {
        
        private string AddressField;
        
        private string AreaChNameField;
        
        private string AreaEnNameField;
        
        private int AreaIDField;
        
        private string AreaIDsField;
        
        private string BankAccountField;
        
        private string BankNameField;
        
        private string BusinessLicenseField;
        
        private string CompanyTelField;
        
        private string CompanyUrlField;
        
        private string ContactCellPhoneField;
        
        private string ContactEmailField;
        
        private string ContactFaxField;
        
        private string ContactNameField;
        
        private string ContactTelField;
        
        private string ContractStatusField;
        
        private string CooperativeStatusField;
        
        private string CustomsPortsField;
        
        private System.Collections.Generic.List<TmsCommonDataService.CustomsPortServiceModel> CustomsPortsListField;
        
        private bool HasClearanceServiceField;
        
        private bool HasPhotoServiceField;
        
        private string IDCardNoField;
        
        private string LegalRepresentativeField;
        
        private string LegalRepresentativeIDCardTypeField;
        
        private string LogisticsCompanyEnNameField;
        
        private int LogisticsCompanyIDField;
        
        private string LogisticsCompanyNameField;
        
        private string LogisticsCompanyNoField;
        
        private string LogisticsCompanyShortNameField;
        
        private string LogisticsCompanyTypeField;
        
        private string LogisticsStateAdvisoryTelField;
        
        private string LogisticsStateAdvisoryUrlField;
        
        private int OrderByField;
        
        private string OrganizationCodeField;
        
        private string PatchField;
        
        private decimal RegisteredCapitalField;
        
        private string RemarkField;
        
        private string SettlementPrincipalTypeField;
        
        private string ShangpinOwnerField;
        
        private string TariffNoField;
        
        private System.Collections.Generic.List<TmsCommonDataService.WarehouseServiceModel> WarehousesListField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address
        {
            get
            {
                return this.AddressField;
            }
            set
            {
                this.AddressField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AreaChName
        {
            get
            {
                return this.AreaChNameField;
            }
            set
            {
                this.AreaChNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AreaEnName
        {
            get
            {
                return this.AreaEnNameField;
            }
            set
            {
                this.AreaEnNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AreaID
        {
            get
            {
                return this.AreaIDField;
            }
            set
            {
                this.AreaIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AreaIDs
        {
            get
            {
                return this.AreaIDsField;
            }
            set
            {
                this.AreaIDsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BankAccount
        {
            get
            {
                return this.BankAccountField;
            }
            set
            {
                this.BankAccountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BankName
        {
            get
            {
                return this.BankNameField;
            }
            set
            {
                this.BankNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BusinessLicense
        {
            get
            {
                return this.BusinessLicenseField;
            }
            set
            {
                this.BusinessLicenseField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CompanyTel
        {
            get
            {
                return this.CompanyTelField;
            }
            set
            {
                this.CompanyTelField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CompanyUrl
        {
            get
            {
                return this.CompanyUrlField;
            }
            set
            {
                this.CompanyUrlField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ContactCellPhone
        {
            get
            {
                return this.ContactCellPhoneField;
            }
            set
            {
                this.ContactCellPhoneField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ContactEmail
        {
            get
            {
                return this.ContactEmailField;
            }
            set
            {
                this.ContactEmailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ContactFax
        {
            get
            {
                return this.ContactFaxField;
            }
            set
            {
                this.ContactFaxField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ContactName
        {
            get
            {
                return this.ContactNameField;
            }
            set
            {
                this.ContactNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ContactTel
        {
            get
            {
                return this.ContactTelField;
            }
            set
            {
                this.ContactTelField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ContractStatus
        {
            get
            {
                return this.ContractStatusField;
            }
            set
            {
                this.ContractStatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CooperativeStatus
        {
            get
            {
                return this.CooperativeStatusField;
            }
            set
            {
                this.CooperativeStatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomsPorts
        {
            get
            {
                return this.CustomsPortsField;
            }
            set
            {
                this.CustomsPortsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<TmsCommonDataService.CustomsPortServiceModel> CustomsPortsList
        {
            get
            {
                return this.CustomsPortsListField;
            }
            set
            {
                this.CustomsPortsListField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool HasClearanceService
        {
            get
            {
                return this.HasClearanceServiceField;
            }
            set
            {
                this.HasClearanceServiceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool HasPhotoService
        {
            get
            {
                return this.HasPhotoServiceField;
            }
            set
            {
                this.HasPhotoServiceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IDCardNo
        {
            get
            {
                return this.IDCardNoField;
            }
            set
            {
                this.IDCardNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LegalRepresentative
        {
            get
            {
                return this.LegalRepresentativeField;
            }
            set
            {
                this.LegalRepresentativeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LegalRepresentativeIDCardType
        {
            get
            {
                return this.LegalRepresentativeIDCardTypeField;
            }
            set
            {
                this.LegalRepresentativeIDCardTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LogisticsCompanyEnName
        {
            get
            {
                return this.LogisticsCompanyEnNameField;
            }
            set
            {
                this.LogisticsCompanyEnNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LogisticsCompanyID
        {
            get
            {
                return this.LogisticsCompanyIDField;
            }
            set
            {
                this.LogisticsCompanyIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LogisticsCompanyName
        {
            get
            {
                return this.LogisticsCompanyNameField;
            }
            set
            {
                this.LogisticsCompanyNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LogisticsCompanyNo
        {
            get
            {
                return this.LogisticsCompanyNoField;
            }
            set
            {
                this.LogisticsCompanyNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LogisticsCompanyShortName
        {
            get
            {
                return this.LogisticsCompanyShortNameField;
            }
            set
            {
                this.LogisticsCompanyShortNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LogisticsCompanyType
        {
            get
            {
                return this.LogisticsCompanyTypeField;
            }
            set
            {
                this.LogisticsCompanyTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LogisticsStateAdvisoryTel
        {
            get
            {
                return this.LogisticsStateAdvisoryTelField;
            }
            set
            {
                this.LogisticsStateAdvisoryTelField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LogisticsStateAdvisoryUrl
        {
            get
            {
                return this.LogisticsStateAdvisoryUrlField;
            }
            set
            {
                this.LogisticsStateAdvisoryUrlField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OrderBy
        {
            get
            {
                return this.OrderByField;
            }
            set
            {
                this.OrderByField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OrganizationCode
        {
            get
            {
                return this.OrganizationCodeField;
            }
            set
            {
                this.OrganizationCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Patch
        {
            get
            {
                return this.PatchField;
            }
            set
            {
                this.PatchField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal RegisteredCapital
        {
            get
            {
                return this.RegisteredCapitalField;
            }
            set
            {
                this.RegisteredCapitalField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Remark
        {
            get
            {
                return this.RemarkField;
            }
            set
            {
                this.RemarkField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SettlementPrincipalType
        {
            get
            {
                return this.SettlementPrincipalTypeField;
            }
            set
            {
                this.SettlementPrincipalTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ShangpinOwner
        {
            get
            {
                return this.ShangpinOwnerField;
            }
            set
            {
                this.ShangpinOwnerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TariffNo
        {
            get
            {
                return this.TariffNoField;
            }
            set
            {
                this.TariffNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<TmsCommonDataService.WarehouseServiceModel> WarehousesList
        {
            get
            {
                return this.WarehousesListField;
            }
            set
            {
                this.WarehousesListField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SettlementPrincipalServiceModel", Namespace="http://schemas.datacontract.org/2004/07/Shangpin.Logistic.ServiceLibrary.Entity")]
    public partial class SettlementPrincipalServiceModel : object
    {
        
        private string SettlementPrincipalIDField;
        
        private string SettlementPrincipalNOField;
        
        private string SettlementPrincipalNameField;
        
        private short SortValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SettlementPrincipalID
        {
            get
            {
                return this.SettlementPrincipalIDField;
            }
            set
            {
                this.SettlementPrincipalIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SettlementPrincipalNO
        {
            get
            {
                return this.SettlementPrincipalNOField;
            }
            set
            {
                this.SettlementPrincipalNOField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SettlementPrincipalName
        {
            get
            {
                return this.SettlementPrincipalNameField;
            }
            set
            {
                this.SettlementPrincipalNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short SortValue
        {
            get
            {
                return this.SortValueField;
            }
            set
            {
                this.SortValueField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ValueAddedServiceFeeServiceModel", Namespace="http://schemas.datacontract.org/2004/07/Shangpin.Logistic.ServiceLibrary.Entity")]
    public partial class ValueAddedServiceFeeServiceModel : object
    {
        
        private decimal CumulativeFeeField;
        
        private string CumulativeUnitField;
        
        private int CurrencyIDField;
        
        private bool IsEnableField;
        
        private int LeastCountField;
        
        private decimal LeastFeeField;
        
        private int OrderByField;
        
        private string RemarkField;
        
        private string UnitField;
        
        private int ValueAddedServiceFeeIDField;
        
        private string ValueAddedServiceFeeNameField;
        
        private string ValueAddedServiceFeeNoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal CumulativeFee
        {
            get
            {
                return this.CumulativeFeeField;
            }
            set
            {
                this.CumulativeFeeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CumulativeUnit
        {
            get
            {
                return this.CumulativeUnitField;
            }
            set
            {
                this.CumulativeUnitField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CurrencyID
        {
            get
            {
                return this.CurrencyIDField;
            }
            set
            {
                this.CurrencyIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsEnable
        {
            get
            {
                return this.IsEnableField;
            }
            set
            {
                this.IsEnableField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LeastCount
        {
            get
            {
                return this.LeastCountField;
            }
            set
            {
                this.LeastCountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal LeastFee
        {
            get
            {
                return this.LeastFeeField;
            }
            set
            {
                this.LeastFeeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OrderBy
        {
            get
            {
                return this.OrderByField;
            }
            set
            {
                this.OrderByField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Remark
        {
            get
            {
                return this.RemarkField;
            }
            set
            {
                this.RemarkField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Unit
        {
            get
            {
                return this.UnitField;
            }
            set
            {
                this.UnitField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ValueAddedServiceFeeID
        {
            get
            {
                return this.ValueAddedServiceFeeIDField;
            }
            set
            {
                this.ValueAddedServiceFeeIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ValueAddedServiceFeeName
        {
            get
            {
                return this.ValueAddedServiceFeeNameField;
            }
            set
            {
                this.ValueAddedServiceFeeNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ValueAddedServiceFeeNo
        {
            get
            {
                return this.ValueAddedServiceFeeNoField;
            }
            set
            {
                this.ValueAddedServiceFeeNoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ContractServiceModel", Namespace="http://schemas.datacontract.org/2004/07/Shangpin.Logistic.Model.Basic")]
    public partial class ContractServiceModel : object
    {
        
        private TmsCommonDataService.ApprovalStatus ApprovalStatusField;
        
        private string CompanySignatureField;
        
        private System.DateTime CompanySignatureDateField;
        
        private System.DateTime ContractBeginDateField;
        
        private string ContractContentField;
        
        private System.DateTime ContractEndDateField;
        
        private int ContractIDField;
        
        private string ContractNOField;
        
        private string ContractNameField;
        
        private string ContractRemarkField;
        
        private string ContractTypeField;
        
        private int CurrencyIDField;
        
        private string CustomerSignatureField;
        
        private System.DateTime CustomerSignatureDateField;
        
        private string CustomerSignatureJobField;
        
        private decimal DepositField;
        
        private string IDCardNOField;
        
        private string LegalRepresentativeField;
        
        private string LogisticsCompanyAddressField;
        
        private string LogisticsCompanyContactNameField;
        
        private int LogisticsCompanyIDField;
        
        private string LogisticsCompanyNOField;
        
        private string LogisticsCompanyNameField;
        
        private string LogisticsCompanyShortNameField;
        
        private int ParentContractIDField;
        
        private string ServiceTypeField;
        
        private string SettlementExchangRateTypeField;
        
        private int SettlementPeriodField;
        
        private string SettlementPrincipalTypeField;
        
        private TmsCommonDataService.ContractStatus StatusField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TmsCommonDataService.ApprovalStatus ApprovalStatus
        {
            get
            {
                return this.ApprovalStatusField;
            }
            set
            {
                this.ApprovalStatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CompanySignature
        {
            get
            {
                return this.CompanySignatureField;
            }
            set
            {
                this.CompanySignatureField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CompanySignatureDate
        {
            get
            {
                return this.CompanySignatureDateField;
            }
            set
            {
                this.CompanySignatureDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ContractBeginDate
        {
            get
            {
                return this.ContractBeginDateField;
            }
            set
            {
                this.ContractBeginDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ContractContent
        {
            get
            {
                return this.ContractContentField;
            }
            set
            {
                this.ContractContentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ContractEndDate
        {
            get
            {
                return this.ContractEndDateField;
            }
            set
            {
                this.ContractEndDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ContractID
        {
            get
            {
                return this.ContractIDField;
            }
            set
            {
                this.ContractIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ContractNO
        {
            get
            {
                return this.ContractNOField;
            }
            set
            {
                this.ContractNOField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ContractName
        {
            get
            {
                return this.ContractNameField;
            }
            set
            {
                this.ContractNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ContractRemark
        {
            get
            {
                return this.ContractRemarkField;
            }
            set
            {
                this.ContractRemarkField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ContractType
        {
            get
            {
                return this.ContractTypeField;
            }
            set
            {
                this.ContractTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CurrencyID
        {
            get
            {
                return this.CurrencyIDField;
            }
            set
            {
                this.CurrencyIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerSignature
        {
            get
            {
                return this.CustomerSignatureField;
            }
            set
            {
                this.CustomerSignatureField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CustomerSignatureDate
        {
            get
            {
                return this.CustomerSignatureDateField;
            }
            set
            {
                this.CustomerSignatureDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerSignatureJob
        {
            get
            {
                return this.CustomerSignatureJobField;
            }
            set
            {
                this.CustomerSignatureJobField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Deposit
        {
            get
            {
                return this.DepositField;
            }
            set
            {
                this.DepositField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IDCardNO
        {
            get
            {
                return this.IDCardNOField;
            }
            set
            {
                this.IDCardNOField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LegalRepresentative
        {
            get
            {
                return this.LegalRepresentativeField;
            }
            set
            {
                this.LegalRepresentativeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LogisticsCompanyAddress
        {
            get
            {
                return this.LogisticsCompanyAddressField;
            }
            set
            {
                this.LogisticsCompanyAddressField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LogisticsCompanyContactName
        {
            get
            {
                return this.LogisticsCompanyContactNameField;
            }
            set
            {
                this.LogisticsCompanyContactNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LogisticsCompanyID
        {
            get
            {
                return this.LogisticsCompanyIDField;
            }
            set
            {
                this.LogisticsCompanyIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LogisticsCompanyNO
        {
            get
            {
                return this.LogisticsCompanyNOField;
            }
            set
            {
                this.LogisticsCompanyNOField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LogisticsCompanyName
        {
            get
            {
                return this.LogisticsCompanyNameField;
            }
            set
            {
                this.LogisticsCompanyNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LogisticsCompanyShortName
        {
            get
            {
                return this.LogisticsCompanyShortNameField;
            }
            set
            {
                this.LogisticsCompanyShortNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ParentContractID
        {
            get
            {
                return this.ParentContractIDField;
            }
            set
            {
                this.ParentContractIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ServiceType
        {
            get
            {
                return this.ServiceTypeField;
            }
            set
            {
                this.ServiceTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SettlementExchangRateType
        {
            get
            {
                return this.SettlementExchangRateTypeField;
            }
            set
            {
                this.SettlementExchangRateTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SettlementPeriod
        {
            get
            {
                return this.SettlementPeriodField;
            }
            set
            {
                this.SettlementPeriodField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SettlementPrincipalType
        {
            get
            {
                return this.SettlementPrincipalTypeField;
            }
            set
            {
                this.SettlementPrincipalTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TmsCommonDataService.ContractStatus Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ApprovalStatus", Namespace="http://schemas.datacontract.org/2004/07/Shangpin.Logistic.Model.Enum.Basic")]
    public enum ApprovalStatus : byte
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Pending = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Approved = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Disapprove = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceResultModel", Namespace="http://schemas.datacontract.org/2004/07/Shangpin.Logistic.ServiceLibrary.Entity")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TmsCommonDataService.DeliveryMethodResultModel))]
    public partial class ServiceResultModel : object
    {
        
        private string MessageField;
        
        private int MessageCodeField;
        
        private bool SuccessedField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MessageCode
        {
            get
            {
                return this.MessageCodeField;
            }
            set
            {
                this.MessageCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Successed
        {
            get
            {
                return this.SuccessedField;
            }
            set
            {
                this.SuccessedField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DeliveryMethodResultModel", Namespace="http://schemas.datacontract.org/2004/07/Shangpin.Logistic.ServiceLibrary.Entity")]
    public partial class DeliveryMethodResultModel : TmsCommonDataService.ServiceResultModel
    {
        
        private System.Collections.Generic.List<TmsCommonDataService.DeliveryMethodServiceModel> DeliveryMethodResultField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<TmsCommonDataService.DeliveryMethodServiceModel> DeliveryMethodResult
        {
            get
            {
                return this.DeliveryMethodResultField;
            }
            set
            {
                this.DeliveryMethodResultField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DeliveryMethodServiceModel", Namespace="http://schemas.datacontract.org/2004/07/Shangpin.Logistic.ServiceLibrary.Entity")]
    public partial class DeliveryMethodServiceModel : object
    {
        
        private int AreaIDField;
        
        private string AreaNameField;
        
        private long DeliveryMethodIDField;
        
        private string DeliveryMethodNameField;
        
        private int DeliveryMethodNoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AreaID
        {
            get
            {
                return this.AreaIDField;
            }
            set
            {
                this.AreaIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AreaName
        {
            get
            {
                return this.AreaNameField;
            }
            set
            {
                this.AreaNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long DeliveryMethodID
        {
            get
            {
                return this.DeliveryMethodIDField;
            }
            set
            {
                this.DeliveryMethodIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DeliveryMethodName
        {
            get
            {
                return this.DeliveryMethodNameField;
            }
            set
            {
                this.DeliveryMethodNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DeliveryMethodNo
        {
            get
            {
                return this.DeliveryMethodNoField;
            }
            set
            {
                this.DeliveryMethodNoField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TmsCommonDataService.ICommonDataService")]
    public interface ICommonDataService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommonDataService/GetWarehouseByCondition", ReplyAction="http://tempuri.org/ICommonDataService/GetWarehouseByConditionResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<TmsCommonDataService.WarehouseServiceModel>> GetWarehouseByConditionAsync(TmsCommonDataService.WarehouseServiceSearchModel searchModel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommonDataService/GetValueAddedServiceFees", ReplyAction="http://tempuri.org/ICommonDataService/GetValueAddedServiceFeesResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<TmsCommonDataService.ValueAddedServiceFeeServiceModel>> GetValueAddedServiceFeesAsync(TmsCommonDataService.ValueAddedServiceFeeServiceSearchModel searchModel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommonDataService/GetContracts", ReplyAction="http://tempuri.org/ICommonDataService/GetContractsResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<TmsCommonDataService.ContractServiceModel>> GetContractsAsync(TmsCommonDataService.ContractServiceSearchModel searchModel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommonDataService/GetCustomsPorts", ReplyAction="http://tempuri.org/ICommonDataService/GetCustomsPortsResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<TmsCommonDataService.CustomsPortServiceModel>> GetCustomsPortsAsync(TmsCommonDataService.CustomsPortServiceSearchModel searchModel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommonDataService/GetLogisticsCompanies", ReplyAction="http://tempuri.org/ICommonDataService/GetLogisticsCompaniesResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<TmsCommonDataService.LogisticsCompanyServiceModel>> GetLogisticsCompaniesAsync(TmsCommonDataService.LogisticsCompanyServiceSearchModel searchModel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommonDataService/GetDeliveryMethodByAreaIds", ReplyAction="http://tempuri.org/ICommonDataService/GetDeliveryMethodByAreaIdsResponse")]
        System.Threading.Tasks.Task<TmsCommonDataService.DeliveryMethodResultModel> GetDeliveryMethodByAreaIdsAsync(System.Collections.Generic.List<int> countryIds);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    public interface ICommonDataServiceChannel : TmsCommonDataService.ICommonDataService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    public partial class CommonDataServiceClient : System.ServiceModel.ClientBase<TmsCommonDataService.ICommonDataService>, TmsCommonDataService.ICommonDataService
    {
        
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public CommonDataServiceClient() : 
                base(CommonDataServiceClient.GetDefaultBinding(), CommonDataServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.WSHttpBinding_ICommonDataService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CommonDataServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(CommonDataServiceClient.GetBindingForEndpoint(endpointConfiguration), CommonDataServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CommonDataServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(CommonDataServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CommonDataServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(CommonDataServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CommonDataServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<TmsCommonDataService.WarehouseServiceModel>> GetWarehouseByConditionAsync(TmsCommonDataService.WarehouseServiceSearchModel searchModel)
        {
            return base.Channel.GetWarehouseByConditionAsync(searchModel);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<TmsCommonDataService.ValueAddedServiceFeeServiceModel>> GetValueAddedServiceFeesAsync(TmsCommonDataService.ValueAddedServiceFeeServiceSearchModel searchModel)
        {
            return base.Channel.GetValueAddedServiceFeesAsync(searchModel);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<TmsCommonDataService.ContractServiceModel>> GetContractsAsync(TmsCommonDataService.ContractServiceSearchModel searchModel)
        {
            return base.Channel.GetContractsAsync(searchModel);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<TmsCommonDataService.CustomsPortServiceModel>> GetCustomsPortsAsync(TmsCommonDataService.CustomsPortServiceSearchModel searchModel)
        {
            return base.Channel.GetCustomsPortsAsync(searchModel);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<TmsCommonDataService.LogisticsCompanyServiceModel>> GetLogisticsCompaniesAsync(TmsCommonDataService.LogisticsCompanyServiceSearchModel searchModel)
        {
            return base.Channel.GetLogisticsCompaniesAsync(searchModel);
        }
        
        public System.Threading.Tasks.Task<TmsCommonDataService.DeliveryMethodResultModel> GetDeliveryMethodByAreaIdsAsync(System.Collections.Generic.List<int> countryIds)
        {
            return base.Channel.GetDeliveryMethodByAreaIdsAsync(countryIds);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WSHttpBinding_ICommonDataService))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WSHttpBinding_ICommonDataService))
            {
                return new System.ServiceModel.EndpointAddress("http://qa.tmsservice.shangpin.com/CommonDataService.svc/CommonDataService");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return CommonDataServiceClient.GetBindingForEndpoint(EndpointConfiguration.WSHttpBinding_ICommonDataService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return CommonDataServiceClient.GetEndpointAddress(EndpointConfiguration.WSHttpBinding_ICommonDataService);
        }
        
        public enum EndpointConfiguration
        {
            
            WSHttpBinding_ICommonDataService,
        }
    }
}
